

client:
	gcc -o enc_client enc_client.c
	gcc -o dec_client dec_client.c

server:
	gcc -o enc_server enc_server.c
	gcc -o dec_server dec_server.c

key:
	gcc -o keygen keygen.c

all: client server key